name: context # name of the workflow 

# This defines the event that triggers the workflow
on: [push] # triggeres 

env:
  project: roboshop
  component: user
  enviroment: dev 


jobs:
  access-the-secerts:
    # The type of virtual machine the job will run on
    runs-on: ubuntu-latest

    steps:
      # Step 1: Print the classic message in the logs
      # - name: context-info
      #   run: | 
      #    echo "${{ toJson(github) }}"
      #    echo "branch_name: ${{ github.ref }}"

      - name: printing the enviroment
        run: |
          echo "project: $project"
          echo "component: $component"
          echo "enviroment: $enviroment" 

      - name: accessing the sercets
        run : |
          echo "my db_url is : ${{ secrets.DBURL }}"

      - name: Print  variable
        run: echo "The database host is ${{ vars.dburl }}"

      - name: image version and name 
        id: tages 
        run : | 
          echo "version=1.9.0" >> $GITHUB_OUTPUT
          echo "image-name=user" >> $GITHUB_OUTPUT

      - name: printing the image name and verison
        run: |
          echo "image-version is : ${{ steps.tages.output.version }}"
          echo "image-name is : ${{ steps.tages.output.iamge-name }}"



