name: context # name of the workflow 

# This defines the event that triggers the workflow
on: [push] # triggeres 

env:
  project: roboshop
  component: user
  enviroment: dev 


jobs:
  access-the-secerts:
    # The type of virtual machine the job will run on
    runs-on: ubuntu-latest
    outputs:
      image-name: ${{ steps.tages.outputs.name }}
      image-version: ${{ steps.tages.outputs.lastname }}

    steps:
      # Step 1: Print the classic message in the logs
      # - name: context-info
      #   run: | 
      #    echo "${{ toJson(github) }}"
      #    echo "branch_name: ${{ github.ref }}"

      - name: printing the enviroment
        run: |
          echo "project: $project"
          echo "component: $component"
          echo "enviroment: $enviroment" 

      - name: accessing the sercets
        run : |
          echo "my db_url is : ${{ secrets.DBURL }}"

      - name: Print  variable
        run: echo "The database host is ${{ vars.dburl }}"

      - name: image version and name 
        id: tages 
        run : | 
          echo "version=1.9.0" >> $GITHUB_OUTPUT
          echo "image-name=user" >> $GITHUB_OUTPUT

      - name: printing the image name and verison
        run: |
          echo "image-version is : ${{ steps.tages.outputs.version }}"
          echo "image-name is : ${{ steps.tages.outputs.image-name }}"

      - name: print github env
        run: |
          echo "name=shaikaif" >> $GITHUB_ENV
          echo "lastname=ali" >> $GITHUB_ENV

      - name: print github env
        run: |
          echo "myname is: $name"
          echo "mylastname is: $lastname"
  
  deploy:
    needs: access-the-secerts # means depends on above job
    runs-on: ubuntu-latest # Github hosted runners
    steps:
      - name: print github env in another job
        run: |
          echo "Image Name: ${{ needs.github-context.outputs.name }}"
          echo "Image Version: ${{ needs.github-context.outputs.lastname }}"





