name: CI Example
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Run a script with a secret
        env:
          # Map the GitHub Secret to a usable environment variable
          SUPER_SECRET_KEY: ${{ secrets.YUSUF_ALI }} 
        run: |
          echo "Executing command using the mapped environment variable..."
          python my_script.py --token $SUPER_SECRET_KEY

